name: update-uBlacklist-subscription

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:sid
    steps:
    - uses: actions/checkout@v2
    - name: Install environment deps
      run: |
        apt-get update -y
        apt-get install --no-install-recommends -y python3-dev python3-pip
    - name: update Blocklist
      run: |
        pip3 install -r requirements.txt
        cd src && \
          python3 filter_content_farm.py && \
          python3 filter_ml_translation.py
    - name: push
      uses: github-actions-x/commit@v2.8
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'update subscription'
        force-add: 'true'
        files: ml-translation_v1.txt content-farm_v1.txt
        commit-message: "update uBlacklist subscription"
        push-branch: master
        rebase: 'true'
