name: update-uBlacklist-subscription

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install environment deps
      run: |
        apt-get update -y
        apt-get install --no-install-recommends -y python3-dev python3-pip git
    - name: update Blocklist
      run: |
        pip3 install -r src/requirements.txt
        python3 src/filter_content_farm.py
        python3 src/filter_ml_translation.py
    - name: push
      uses: github-actions-x/commit@v2.8
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        force-add: 'true'
        files: ml-translation_v1.txt content-farm_v1.txt
        commit-message: "update subscription"
        push-branch: master
        # rebase: 'true'
